theme = "tokyonight"

[editor]
auto-format = true
bufferline = "multiple"
soft-wrap.enable = true
cursorline = true
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
skip-levels = 1
character = "|"

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "-"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-," = "goto_previous_buffer"
"C-." = "goto_next_buffer"
"C-w" = ":buffer-close"
"C-s" = ":w"
"C-/" = "repeat_last_motion"
"C-A-r" = ":config-reload"

